name: garage
channels:
  - conda-forge
dependencies:
    - python==3.5
    - pip # required so that conda doesn't complain
    - numpy==1.14.5 # pycma requires numpy to install (smh)
    - pre_commit  # See https://github.com/pre-commit/pre-commit/issues/701
    - pip:
        - -e .[all]
        - -e .[dev]
        # install sister packages to make sure environments stay compatible
        - git+https://github.com/rlworkgroup/metaworlds.git@master#egg=metaworlds
        - git+https://github.com/rlworkgroup/viskit.git@master#egg=viskit
