name: rllab3
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.anaconda.org/menpo
dependencies:
    - python==3.5.2
    - numpy==1.12.0
    - scipy
    - path.py
    - python-dateutil
    - joblib==0.10.3
    - mako
    - ipywidgets
    - flask
    - pybox2d
    - pygame
    - matplotlib
    - pandas
    - mkl-service=1.1.2
    - pip:
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - mujoco-py<1.50.2,>=1.50.1
        - cached_property
        - cloudpickle
        - git+https://github.com/Lasagne/Lasagne.git@7992faa80fa5233a786e2582a605e854cea7d1cf#egg=Lasagne
        - git+https://github.com/Theano/Theano.git@2c19431b165aaf8289d1e6654988c64f4bb234e1#egg=Theano
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - git+https://github.com/deepmind/dm_control.git#egg=dm_control
        - awscli
        - gym==0.10.5
        - pyglet
        - jupyter
        - hyperopt
        - polling
        - tensorboard
        - jsonmerge
        - protobuf
