name: garage
channels:
    - https://conda.anaconda.org/menpo
    - https://conda.anaconda.org/conda-forge
dependencies:
    - python==3.6.6
    # Please keep alphabetized
    - mkl-service=1.1.2
    - mkl==2017.0.4
    # cma requires numpy to install
    - numpy==1.14.5
    # dev dependencies below this line
    - pre_commit
    - pip:
        # Please keep alphabetized
        - awscli
        - boto3
        - cached_property
        - cloudpickle
        - cma==1.1.06
        # dm_control throws an error during install about not being able to
        # find a build dependency (absl-py). Later pip executes the `install`
        # command again and the install succeeds because absl-py has been
        # installed. This is stupid, but harmless.
        - git+https://github.com/deepmind/dm_control.git@c24ec9f5f3cb3c25c6571c89c9f60bf3350f5711#egg=dm_control
        - flask
        - gym[all]==0.10.8
        - box2d-py>=2.3.4
        - hyperopt
        - ipdb
        - ipywidgets
        - jsonmerge
        - joblib<0.13,>=0.12
        - jupyter
        - git+https://github.com/Lasagne/Lasagne.git@a61b76fd991f84c50acdb7bea02118899b5fefe1#egg=lasagne
        - mako
        - matplotlib
        - memory_profiler
        - mujoco-py<1.50.2,>=1.50.1
        - pandas
        - path.py
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - polling
        - protobuf
        - psutil
        - pygame
        - pyglet
        - PyOpenGL
        - pyprind
        - python-dateutil
        - pyzmq
        - scikit-image
        - scipy
        - tensorboard
        - tensorflow<1.10,>=1.9.0
        - Theano==1.0.2
        # dev dependencies below this line
        - git+https://github.com/openai/baselines.git@f2729693253c0ef4d4086231d36e0a4307ec1cb3#egg=baselines
        - codacy-coverage
        - coverage
        - coveralls
        - flake8
        - flake8-docstrings==1.3.0
        - flake8-import-order
        - nose2
        - pep8-naming==0.7.0
        - pylint==1.9.2
        - yapf
